make the SSH hook work with amazon linux (#16)

diff --git a/scripts/keymaker-create-account-for-iam-user b/scripts/keymaker-create-account-for-iam-user
--- a/scripts/keymaker-create-account-for-iam-user
+++ b/scripts/keymaker-create-account-for-iam-user
@@ -2,6 +2,7 @@
 
 EX_TEMPFAIL=75
 EX_NOPERM=77
+SUPATH='/usr/sbin'
 
 if getent passwd "$PAM_USER" >/dev/null 2>&1; then
     # Terminate the PAM authentication stack. The SSH client will fail since the user didn't supply a valid public key.
@@ -12,9 +13,13 @@ else
     # Verify that the IAM user exists.
     keymaker get_authorized_keys "$PAM_USER" >/dev/null
     NEW_UID=$(keymaker get_uid "$PAM_USER")
-    adduser "$PAM_USER" --disabled-password --gecos "$PAM_USER" --uid "$NEW_UID"
+    if ! [ $(command -v useradd > /dev/null) ]; then
+        ${SUPATH}/useradd "$PAM_USER" --comment "$PAM_USER" --uid "$NEW_UID"
+    else
+        ${SUPATH}/adduser "$PAM_USER" --disabled-password --gecos "$PAM_USER" --uid "$NEW_UID"
+    fi   
     for group in $(keymaker get_groups "$PAM_USER"); do
-        usermod --append --groups "$group" "$PAM_USER" || echo "$0: Error while adding user to group"
+        ${SUPATH}/usermod --append --groups "$group" "$PAM_USER" || echo "$0: Error while adding user to group"
     done
     echo "Keymaker: Your user account has been replicated onto this host, but SSH will not recognize it until you reconnect."
     echo "Keymaker: Connect again to log in to your account."
