WIP

diff --git a/scripts/keymaker-create-account-for-iam-user b/scripts/keymaker-create-account-for-iam-user
--- a/scripts/keymaker-create-account-for-iam-user
+++ b/scripts/keymaker-create-account-for-iam-user
@@ -12,7 +12,10 @@ else
     # Verify that the IAM user exists.
     keymaker get_authorized_keys "$PAM_USER" > /dev/null
     adduser "$PAM_USER" --disabled-password --gecos "$PAM_USER" --uid "$(keymaker get_uid '$PAM_USER')"
-    echo "$0: Your user account has been created on demand, but SSH will not know about it until you reconnect." > /dev/stderr
-    echo "$0: Connect with SSH again to log in to your account." > /dev/stderr
+    for group in "$(keymaker get_groups '$PAM_USER')"; do
+        usermod --append --groups "$group" "$PAM_USER" || echo "$0: Error while adding user to group"
+    done
+    echo "$0: Your user account has been created on demand, but SSH will not know about it until you reconnect."
+    echo "$0: Connect with SSH again to log in to your account."
     exit $EX_TEMPFAIL
 fi
